line_length:
- 500 # warning
- 800 # error

function_body_length:
- 200 # error
- 150 # warning

force_cast:
- severity: error

disabled_rules:
- leading_whitespace
- trailing_whitespace
- type_name
- vertical_whitespace
- private_over_fileprivate
- comma
- colon
- trailing_semicolon
- class_delegate_protocol
excluded:
- Pods
