os: osx
language: objective-c
osx_image: xcode11
before_install:
   - rvm use system
   - sudo gem install cocoapods
script:
  - set -o pipefail && xcodebuild build -workspace MyBujo2.0.xcworkspace -scheme MyBujo2.0 -sdk iphonesimulator13.2 -destination 'name=iPhone 8,OS=13.2' ONLY_ACTIVE_ARCH=NO | xcpretty